-- Migration: Add nutrition column to recipes table
-- This enables storing per-serving nutrition information generated by AI

-- Add nutrition JSONB column to recipes table
-- Structure: { "calories": number, "protein": number, "carbs": number, "fat": number }
ALTER TABLE public.recipes 
ADD COLUMN IF NOT EXISTS nutrition JSONB;

-- Add comment for documentation
COMMENT ON COLUMN public.recipes.nutrition IS 'Nutrition information per serving: { calories: kcal, protein: g, carbs: g, fat: g }';
