// This file is auto-generated by scripts/buildRecipeLibrary.ts
// Do not edit manually
import type { Recipe } from "./types/recipe";
import data from "./recipes.generated.json";

export const recipes: Recipe[] = data as Recipe[];
